'use strict';
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {Pool}=require('pg');
const PORT=process.env.PORT||3000,DATABASE_URL=process.env.DATABASE_URL;
const ADMIN='Mr.Russian',CHANNELS=['general','gaming','casino','memes','announcements'];
if(!DATABASE_URL){console.error('DATABASE_URL is required.');process.exit(1)}
const pool=new Pool({connectionString:DATABASE_URL,ssl:{rejectUnauthorized:false},max:10,idleTimeoutMillis:30000,connectionTimeoutMillis:10000});
const own=(o,k)=>Object.prototype.hasOwnProperty.call(o,k);
const th=t=>crypto.createHash('sha256').update(t).digest('hex');
const hashPw=(pw,salt)=>crypto.scryptSync(pw,salt,64).toString('hex');
function checkPw(u,pw){try{const a=Buffer.from(hashPw(pw,u.salt),'hex'),b=Buffer.from(u.hash,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b)}catch{return false}}
const hits=new Map();
function limited(k,max,ms){const n=Date.now(),a=(hits.get(k)||[]).filter(t=>n-t<ms);hits.set(k,a);return a.length>=max}
function hit(k){const a=hits.get(k)||[];a.push(Date.now());hits.set(k,a)}
setInterval(()=>{const n=Date.now();for(const[k,a]of hits){const f=a.filter(t=>n-t<3600000);f.length?hits.set(k,f):hits.delete(k)}},600000).unref();

async function init(){
 await pool.query(`CREATE TABLE IF NOT EXISTS users(username_key TEXT PRIMARY KEY,username TEXT NOT NULL,balance BIGINT NOT NULL DEFAULT 1000,admin BOOLEAN NOT NULL DEFAULT FALSE,last_seen BIGINT NOT NULL DEFAULT 0,forced BOOLEAN NOT NULL DEFAULT FALSE,salt TEXT,hash TEXT,bonus_at BIGINT NOT NULL DEFAULT 0)`);
 await pool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS bonus_at BIGINT NOT NULL DEFAULT 0`);
 await pool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS profile JSONB NOT NULL DEFAULT '{}'::jsonb`);
 await pool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS title TEXT NOT NULL DEFAULT 'Rookie'`);
 await pool.query(`CREATE TABLE IF NOT EXISTS gartic_state(id INTEGER PRIMARY KEY DEFAULT 1,prompt TEXT NOT NULL,round INTEGER NOT NULL DEFAULT 0,phase TEXT NOT NULL DEFAULT 'drawing',started_at BIGINT NOT NULL DEFAULT 0)`);
 await pool.query(`CREATE TABLE IF NOT EXISTS gartic_drawings(id BIGSERIAL PRIMARY KEY,round INTEGER NOT NULL,username_key TEXT NOT NULL REFERENCES users(username_key) ON DELETE CASCADE,drawing TEXT NOT NULL,created_at BIGINT NOT NULL)`);
 await pool.query(`CREATE INDEX IF NOT EXISTS gartic_drawings_round_idx ON gartic_drawings(round)`);
 await pool.query(`CREATE TABLE IF NOT EXISTS gartic_votes(round INTEGER NOT NULL,drawing_id BIGINT NOT NULL REFERENCES gartic_drawings(id) ON DELETE CASCADE,username_key TEXT NOT NULL REFERENCES users(username_key) ON DELETE CASCADE,PRIMARY KEY(round,drawing_id,username_key))`);
 await pool.query(`CREATE TABLE IF NOT EXISTS site_settings(key TEXT PRIMARY KEY,value TEXT NOT NULL)`);
 await pool.query(`INSERT INTO site_settings(key,value) VALUES('announcement','Welcome to Mr.Russians Casino!') ON CONFLICT(key) DO NOTHING`);

 await pool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS last_ip_hash TEXT`);
 await pool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS last_device_hash TEXT`);
 await pool.query(`CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,username_key TEXT NOT NULL REFERENCES users(username_key) ON DELETE CASCADE,expires_at BIGINT NOT NULL)`);
 await pool.query(`CREATE TABLE IF NOT EXISTS chat_messages(id BIGSERIAL PRIMARY KEY,channel TEXT NOT NULL,username TEXT NOT NULL,message TEXT NOT NULL,created_at BIGINT NOT NULL)`);
 await pool.query(`CREATE INDEX IF NOT EXISTS chat_messages_channel_idx ON chat_messages(channel,id)`);
 await pool.query(`CREATE TABLE IF NOT EXISTS game_rounds(username_key TEXT PRIMARY KEY,game TEXT NOT NULL,state JSONB NOT NULL,updated_at BIGINT NOT NULL)`);
 await pool.query(`CREATE TABLE IF NOT EXISTS bans(username_key TEXT PRIMARY KEY,ip_hash TEXT,device_hash TEXT,reason TEXT NOT NULL DEFAULT '',created_at BIGINT NOT NULL,created_by TEXT NOT NULL)`);
 await pool.query(`CREATE INDEX IF NOT EXISTS bans_ip_idx ON bans(ip_hash)`);
 await pool.query(`CREATE INDEX IF NOT EXISTS bans_device_idx ON bans(device_hash)`);
 await pool.query('DELETE FROM sessions WHERE expires_at < $1',[Date.now()]);
 const r=await pool.query('SELECT * FROM users WHERE username_key=$1',[ADMIN.toLowerCase()]); let admin=r.rows[0];
 if(!admin){const salt=crypto.randomBytes(16).toString('hex'),hash=process.env.ADMIN_PASSWORD&&process.env.ADMIN_PASSWORD.length>=8?hashPw(process.env.ADMIN_PASSWORD,salt):null;await pool.query(`INSERT INTO users(username_key,username,balance,admin,last_seen,forced,salt,hash) VALUES($1,$2,100000,true,0,false,$3,$4)`,[ADMIN.toLowerCase(),ADMIN,salt,hash])}
 else if(process.env.ADMIN_PASSWORD&&process.env.ADMIN_PASSWORD.length>=8&&!checkPw(admin,process.env.ADMIN_PASSWORD)){const salt=crypto.randomBytes(16).toString('hex'),hash=hashPw(process.env.ADMIN_PASSWORD,salt);await pool.query('UPDATE users SET salt=$1,hash=$2,admin=true WHERE username_key=$3',[salt,hash,ADMIN.toLowerCase()]);await pool.query('DELETE FROM sessions WHERE username_key=$1',[ADMIN.toLowerCase()])}
}
async function getUser(name){const k=String(name||'').toLowerCase();const r=await pool.query('SELECT * FROM users WHERE username_key=$1',[k]);return r.rows[0]||null}
const DEFAULT_PROFILE={frame:'neon-orbit',nameStyle:'gradient',nameColor:'#ffd166',effect:'glow',banner:'aurora',badge:'✦',title:'Rookie'};
const pub=u=>({username:u.username,balance:Number(u.balance),admin:!!u.admin,profile:{...DEFAULT_PROFILE,...(u.profile||{})},title:u.title||'Rookie'});
const deviceOf=req=>{const m=String(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('casino_device='));return m?m.slice('casino_device='.length):null};
const ipOf=req=>{const x=(req.headers['x-forwarded-for']||'').split(',').map(v=>v.trim()).filter(Boolean);return x.length?x[x.length-1]:(req.socket.remoteAddress||'?')};
function readBody(req){return new Promise((ok,no)=>{let s='';req.on('data',c=>{s+=c;if(s.length>20000){no(new Error('Request too large'));req.destroy()}});req.on('end',()=>{try{ok(s?JSON.parse(s):{})}catch(e){no(new Error('Bad request'))}});req.on('error',no)})}
async function banInfo(req){const ip=ipOf(req),device=deviceOf(req);const ipHash=th(ip),deviceHash=device?th(device):null;const q=await pool.query('SELECT * FROM bans WHERE (ip_hash=$1) OR ($2::text IS NOT NULL AND device_hash=$2::text)',[ipHash,deviceHash]);return q.rows[0]||null}
async function auth(req){const h=req.headers.authorization||'',cookie=String(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('casino_session='))||'',ct=cookie?cookie.slice('casino_session='.length):'',t=h.startsWith('Bearer ')?h.slice(7):ct;if(!t)return null;const r=await pool.query('SELECT s.*,u.* FROM sessions s JOIN users u ON u.username_key=s.username_key WHERE s.token_hash=$1 AND s.expires_at>$2',[th(t),Date.now()]);if(!r.rows[0])return null;return{u:r.rows[0],t}}
async function newSession(u){const t=crypto.randomBytes(32).toString('hex');await pool.query('INSERT INTO sessions(token_hash,username_key,expires_at) VALUES($1,$2,$3)',[th(t),u.username_key,Date.now()+7*864e5]);return t}
const send=(res,code,obj)=>{res.writeHead(code,{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(obj))};
const fail=(res,code,msg)=>send(res,code,{error:msg});
function sessionCookie(token,secure=true){return `casino_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800${secure?'; Secure':''}`}
function clearSessionCookie(){return 'casino_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0; Secure'}
const int=n=>Number.isSafeInteger(n)?n:Math.floor(Number(n));
function validBet(b){b=int(b);return Number.isSafeInteger(b)&&b>=1&&b<=1000000000?b:null}
function rand(n){return crypto.randomInt(n)}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=rand(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
async function txGame(u,fn){const c=await pool.connect();try{await c.query('BEGIN');const r=await c.query('SELECT * FROM users WHERE username_key=$1 FOR UPDATE',[u.username_key]);if(!r.rows[0])throw Object.assign(new Error('Account not found'),{status:401});const result=await fn(c,r.rows[0]);await c.query('COMMIT');return result}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
async function clearRound(c,key){await c.query('DELETE FROM game_rounds WHERE username_key=$1',[key])}
async function setRound(c,key,game,state){await c.query(`INSERT INTO game_rounds(username_key,game,state,updated_at) VALUES($1,$2,$3,$4) ON CONFLICT(username_key) DO UPDATE SET game=EXCLUDED.game,state=EXCLUDED.state,updated_at=EXCLUDED.updated_at`,[key,game,JSON.stringify(state),Date.now()])}
async function getRound(c,key,game){const r=await c.query('SELECT * FROM game_rounds WHERE username_key=$1 AND game=$2 FOR UPDATE',[key,game]);return r.rows[0]||null}
function change(u,delta){const b=Number(u.balance)+delta;if(!Number.isSafeInteger(b)||b<0||b>9007199254740991)throw Object.assign(new Error('Invalid balance'),{status:400});return b}
const BJ_SUITS=['♠','♥','♦','♣'],BJ_RANKS=['A','2','3','4','5','6','7','8','9','10','J','Q','K'];
function bjValue(hand){let t=0,a=0;for(const c of hand){if(c.r==='A'){a++;t+=11}else if(['J','Q','K'].includes(c.r))t+=10;else t+=Number(c.r)}while(t>21&&a){t-=10;a--}return t}
function bjDeck(){return shuffle(BJ_SUITS.flatMap(s=>BJ_RANKS.map(r=>({r,s}))));}

async function game(u,b){
 const action=String(b.action||'');
 if(!action)throw Object.assign(new Error('Missing game action'),{status:400});
 return txGame(u,async(c,me)=>{
  const sendState=()=>({balance:Number(me.balance)});
  if(['coinflip','dice','slots','roulette','plinko'].includes(action)){
   const bet=validBet(b.bet);if(!bet||bet>Number(me.balance))throw Object.assign(new Error('Not enough fictional coins.'),{status:400});
   let payout=0,data={};
   if(action==='coinflip'){const result=rand(2)?'Heads':'Tails';if(String(b.choice)===result)payout=bet*2;data={result,payout}}
   if(action==='dice'){const result=rand(6)+1,pick=int(b.pick);if(result===pick)payout=bet*5;data={result,payout}}
   if(action==='slots'){const syms=['🍒','🍋','🔔','⭐','7️⃣','💎'];const reels=[syms[rand(syms.length)],syms[rand(syms.length)],syms[rand(syms.length)]];if(reels[0]===reels[1]&&reels[1]===reels[2])payout=bet*8;else if(reels[0]===reels[1]||reels[1]===reels[2]||reels[0]===reels[2])payout=bet*2;data={reels,payout}}
   if(action==='roulette'){const nums=[0,32,15,19,4,21,2,25,17,34,6,27,13,36,11,30,8,23,10,5,24,16,33,1,20,14,31,9,22,18,29,7,28,12,35,3,26];const red=new Set([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]);const n=nums[rand(nums.length)],color=n===0?'green':red.has(n)?'red':'black',choice=String(b.choice);if(choice===color)payout=choice==='green'?bet*14:bet*2;data={number:n,color,payout}}
   if(action==='plinko'){const mults=[10,5,2,1,.5,.3,.5,1,2,5,10];const slot=rand(mults.length),mult=mults[slot];payout=Math.floor(bet*mult);data={slot,mult,payout}}
   me.balance=change(me,payout-bet);await c.query('UPDATE users SET balance=$1,last_seen=$2 WHERE username_key=$3',[me.balance,Date.now(),me.username_key]);return {...data,...sendState()};
  }
  if(action==='bonus'){
   const now=Date.now();if(now-Number(me.bonus_at)<30000)throw Object.assign(new Error('Bonus is not ready yet.'),{status:429});me.balance=change(me,15);await c.query('UPDATE users SET balance=$1,bonus_at=$2,last_seen=$3 WHERE username_key=$4',[me.balance,now,now,me.username_key]);return {amount:15,...sendState()};
  }
  if(action==='bj_start'){
   if(await getRound(c,me.username_key,'blackjack'))throw Object.assign(new Error('Blackjack round already active.'),{status:409});const bet=validBet(b.bet);if(!bet||bet>Number(me.balance))throw Object.assign(new Error('Not enough fictional coins.'),{status:400});const deck=bjDeck(),player=[deck.pop(),deck.pop()],dealer=[deck.pop(),deck.pop()];me.balance-=bet;await setRound(c,me.username_key,'blackjack',{bet,deck,player,dealer});await c.query('UPDATE users SET balance=$1,last_seen=$2 WHERE username_key=$3',[me.balance,Date.now(),me.username_key]);return {player,dealer:[dealer[0],{r:'?',s:'?'}],balance:Number(me.balance),blackjack:bjValue(player)===21};
  }
  if(action==='bj_hit'||action==='bj_stand'){
   const rr=await getRound(c,me.username_key,'blackjack');if(!rr)throw Object.assign(new Error('No active blackjack round.'),{status:400});const st=rr.state;if(action==='bj_hit'){st.player.push(st.deck.pop());const v=bjValue(st.player);if(v>21){await clearRound(c,me.username_key);await c.query('UPDATE users SET balance=$1,last_seen=$2 WHERE username_key=$3',[me.balance,Date.now(),me.username_key]);return {player:st.player,dealer:st.dealer,result:'lose',payout:0,balance:Number(me.balance),done:true,message:'Bust. Round lost.'}}await setRound(c,me.username_key,'blackjack',st);return {player:st.player,dealer:[st.dealer[0],{r:'?',s:'?'}],result:'continue',balance:Number(me.balance),done:false,value:v}}
   while(bjValue(st.dealer)<17)st.dealer.push(st.deck.pop());const p=bjValue(st.player),d=bjValue(st.dealer);let payout=0,result='lose',message='Dealer wins.';if(p<=21&&(d>21||p>d)){payout=st.bet*2;result='win';message='You win!'}else if(p===d){payout=st.bet;result='push';message='Push. Bet returned.'}me.balance=change(me,payout);await clearRound(c,me.username_key);await c.query('UPDATE users SET balance=$1,last_seen=$2 WHERE username_key=$3',[me.balance,Date.now(),me.username_key]);return {player:st.player,dealer:st.dealer,result,payout,balance:Number(me.balance),done:true,message,value:p,dealerValue:d};
  }
  if(action==='mines_start'||action==='mines_open'||action==='mines_cashout'){
   if(action==='mines_start'){if(await getRound(c,me.username_key,'mines'))throw Object.assign(new Error('Mines round already active.'),{status:409});const bet=validBet(b.bet),n=int(b.mines);if(!bet||bet>Number(me.balance)||!Number.isInteger(n)||n<1||n>24)throw Object.assign(new Error('Invalid mines bet/settings.'),{status:400});const set=new Set();while(set.size<n)set.add(rand(25));me.balance-=bet;await setRound(c,me.username_key,'mines',{bet,mines:[...set],opened:[]});await c.query('UPDATE users SET balance=$1,last_seen=$2 WHERE username_key=$3',[me.balance,Date.now(),me.username_key]);return {balance:Number(me.balance),minesCount:n,opened:[]}}
   const rr=await getRound(c,me.username_key,'mines');if(!rr)throw Object.assign(new Error('No active mines round.'),{status:400});const st=rr.state;
   if(action==='mines_open'){const idx=int(b.index);if(!Number.isInteger(idx)||idx<0||idx>=25||st.opened.includes(idx))throw Object.assign(new Error('Invalid tile.'),{status:400});if(st.mines.includes(idx)){await clearRound(c,me.username_key);await c.query('UPDATE users SET balance=$1,last_seen=$2 WHERE username_key=$3',[me.balance,Date.now(),me.username_key]);return {balance:Number(me.balance),mine:true,opened:st.opened,mines:st.mines,done:true,payout:0}}st.opened.push(idx);const safe=25-st.mines.length;let mult=1;for(let k=0;k<st.opened.length;k++)mult*=(25-k)/(safe-k);mult=Math.max(1,mult*.96);if(st.opened.length===safe){const payout=Math.floor(st.bet*mult);me.balance=change(me,payout);await clearRound(c,me.username_key);await c.query('UPDATE users SET balance=$1,last_seen=$2 WHERE username_key=$3',[me.balance,Date.now(),me.username_key]);return {balance:Number(me.balance),safe:true,mult,payout,opened:st.opened,mines:st.mines,done:true}}await setRound(c,me.username_key,'mines',st);return {balance:Number(me.balance),safe:true,mult,opened:st.opened,done:false}}
   const safe=25-st.mines.length;if(st.opened.length===0)throw Object.assign(new Error('Open at least one tile first.'),{status:400});let mult=1;for(let k=0;k<st.opened.length;k++)mult*=(25-k)/(safe-k);mult=Math.max(1,mult*.96);const payout=Math.floor(st.bet*mult);me.balance=change(me,payout);await clearRound(c,me.username_key);await c.query('UPDATE users SET balance=$1,last_seen=$2 WHERE username_key=$3',[me.balance,Date.now(),me.username_key]);return {balance:Number(me.balance),payout,mult,opened:st.opened,mines:st.mines,done:true};
  }
  if(action==='hl_start'||action==='hl_guess'){
   if(action==='hl_start'){if(await getRound(c,me.username_key,'hl'))throw Object.assign(new Error('Round already active.'),{status:409});const bet=validBet(b.bet);if(!bet||bet>Number(me.balance))throw Object.assign(new Error('Not enough fictional coins.'),{status:400});const current=rand(13)+1;me.balance-=bet;await setRound(c,me.username_key,'hl',{bet,current});await c.query('UPDATE users SET balance=$1,last_seen=$2 WHERE username_key=$3',[me.balance,Date.now(),me.username_key]);return {current,balance:Number(me.balance)}}
   const rr=await getRound(c,me.username_key,'hl');if(!rr)throw Object.assign(new Error('No active round.'),{status:400});const choice=String(b.choice);if(choice!=='higher'&&choice!=='lower')throw Object.assign(new Error('Invalid guess.'),{status:400});const next=rand(13)+1,old=rr.state.current;let payout=0;if(next===old)payout=rr.state.bet;else if((choice==='higher'&&next>old)||(choice==='lower'&&next<old))payout=rr.state.bet*2;me.balance=change(me,payout);await clearRound(c,me.username_key);await c.query('UPDATE users SET balance=$1,last_seen=$2 WHERE username_key=$3',[me.balance,Date.now(),me.username_key]);return {old,next,payout,balance:Number(me.balance)}}
  if(action==='risk_start'||action==='risk_pick'){
   if(action==='risk_start'){if(await getRound(c,me.username_key,'risk'))throw Object.assign(new Error('Round already active.'),{status:409});const bet=Number(me.balance);if(!Number.isSafeInteger(bet)||bet<=0)throw Object.assign(new Error('You have no fictional coins left.'),{status:400});me.balance=0;await setRound(c,me.username_key,'risk',{bet,winning:rand(9)});await c.query('UPDATE users SET balance=0,last_seen=$1 WHERE username_key=$2',[Date.now(),me.username_key]);return {balance:0}}
   const rr=await getRound(c,me.username_key,'risk');if(!rr)throw Object.assign(new Error('No active round.'),{status:400});const idx=int(b.index);if(idx<0||idx>8)throw Object.assign(new Error('Invalid square.'),{status:400});const payout=idx===rr.state.winning?rr.state.bet*50:0;me.balance=change(me,payout);await clearRound(c,me.username_key);await c.query('UPDATE users SET balance=$1,last_seen=$2 WHERE username_key=$3',[me.balance,Date.now(),me.username_key]);return {balance:Number(me.balance),payout,winning:rr.state.winning,done:true}}
  if(action==='rr_start'||action==='rr_turn'){
   if(action==='rr_start'){if(await getRound(c,me.username_key,'rr'))throw Object.assign(new Error('Round already active.'),{status:409});const bet=validBet(b.bet);if(!bet||bet>Number(me.balance))throw Object.assign(new Error('Not enough fictional coins.'),{status:400});me.balance-=bet;await setRound(c,me.username_key,'rr',{bet});await c.query('UPDATE users SET balance=$1,last_seen=$2 WHERE username_key=$3',[me.balance,Date.now(),me.username_key]);return {balance:Number(me.balance)}}
   const rr=await getRound(c,me.username_key,'rr');if(!rr)throw Object.assign(new Error('No active round.'),{status:400});const win=rand(2)===1,payout=win?rr.state.bet*2:0;me.balance=change(me,payout);await clearRound(c,me.username_key);await c.query('UPDATE users SET balance=$1,last_seen=$2 WHERE username_key=$3',[me.balance,Date.now(),me.username_key]);return {balance:Number(me.balance),payout,win,done:true}}

  if(['wheel','keno','colorpick','tower','cups','limbo','dice_duel','lucky7','baccarat'].includes(action)){
   const bet=validBet(b.bet);if(!bet||bet>Number(me.balance))throw Object.assign(new Error('Not enough fictional coins.'),{status:400});
   let payout=0,data={};
   if(action==='wheel'){const vals=[0.2,0.5,1,1.5,2,3,5,10],m=vals[rand(vals.length)];payout=Math.floor(bet*m);data={mult:m,label:m+'×'};}
   if(action==='keno'){const picks=Array.isArray(b.picks)?b.picks.map(int).filter(x=>x>=1&&x<=40):[];const uniq=[...new Set(picks)].slice(0,10);const draw=shuffle(Array.from({length:40},(_,i)=>i+1)).slice(0,10);const hitsN=uniq.filter(x=>draw.includes(x)).length;const table={1:[0,2],2:[0,4],3:[0,7],4:[0,12],5:[0,25],6:[0,50],7:[0,100],8:[0,250],9:[0,500],10:[0,1000]};payout=(table[uniq.length]||[0,0])[hitsN] ? bet*(table[uniq.length][hitsN]||0):0;data={draw,hits:hitsN,picks:uniq,payout};}
   if(action==='colorpick'){const colors=['red','blue','green','purple','gold'];const result=colors[rand(colors.length)];if(String(b.choice)===result)payout=bet*4;data={result,payout};}
   if(action==='tower'){const level=Math.min(12,Math.max(1,int(b.level)||1));const success=rand(100)<Math.max(12,92-level*6);payout=success?Math.floor(bet*(1+level*.35)):0;data={level,success,payout};}
   if(action==='cups'){const choice=Math.min(3,Math.max(1,int(b.choice)||1)),win=rand(3)+1===choice;payout=win?bet*3:0;data={choice,win,payout};}
   if(action==='limbo'){const target=Math.min(95,Math.max(5,int(b.target)||50));const height=20+rand(76);const win=height>target;payout=win?Math.floor(bet*(100/Math.max(1,target))*.75):0;data={height,target,win,payout};}
   if(action==='dice_duel'){const you=rand(6)+1,house=rand(6)+1;payout=you>house?bet*2:you===house?bet:0;data={you,house,payout};}
   if(action==='lucky7'){const a=rand(10),c=rand(10),sum=a+c;payout=sum===7?bet*5:sum===14?bet*10:0;data={a,c,sum,payout};}
   if(action==='baccarat'){const p=rand(10)+1,d=rand(10)+1;const winner=p>d?'player':p<d?'banker':'tie';const choice=String(b.choice||'player');payout=winner===choice?(choice==='tie'?bet*8:bet*2):winner==='tie'&&choice!=='tie'?bet:0;data={player:p,banker:d,winner,choice,payout};}
   me.balance=change(me,payout-bet);await c.query('UPDATE users SET balance=$1,last_seen=$2 WHERE username_key=$3',[me.balance,Date.now(),me.username_key]);return {...data,...sendState()};
  }
  throw Object.assign(new Error('Unknown game action'),{status:400});
 });
}

async function main(req,res){
 const url=new URL(req.url,'http://x'),p=url.pathname,proto=req.headers['x-forwarded-proto'];
 if(proto==='http'&&p!=='/healthz'){res.writeHead(301,{Location:'https://'+req.headers.host+req.url});return res.end()}
 if(proto==='https')res.setHeader('Strict-Transport-Security','max-age=63072000; includeSubDomains; preload');
 res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Frame-Options','DENY');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');
 res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; object-src 'none'; form-action 'self'");
 try{
  if(req.method==='GET'&&(p==='/'||p==='/index.html')){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-cache'});return res.end(fs.readFileSync(path.join(__dirname,'public','index.html')))}
  if(p==='/healthz')return send(res,200,{ok:true}); if(!p.startsWith('/api/'))return fail(res,404,'Not found');
  if(req.method==='POST'&&!['/api/login','/api/signup'].includes(p)&&req.headers['x-casino-request']!=='1')return fail(res,403,'Invalid request.');
  const route=req.method+' '+p;
  if(req.method==='POST'&&p==='/api/device'){const existing=deviceOf(req);const token=existing||crypto.randomBytes(32).toString('hex');res.setHeader('Set-Cookie',`casino_device=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=31536000${proto==='https'?'; Secure':''}`);return send(res,200,{ok:true})}
  if(route==='GET /api/leaderboard'){const r=await pool.query('SELECT username,balance FROM users WHERE admin=false ORDER BY balance DESC LIMIT 10');return send(res,200,{top:r.rows.map(u=>({name:u.username,coins:Number(u.balance)}))})}
  if(route==='POST /api/signup'){const ban=await banInfo(req);if(ban)return fail(res,403,'This device/network is banned.');const ip=ipOf(req);if(limited('s'+ip,5,3600000))return fail(res,429,'Too many sign-ups from this network. Try again later.');const b=await readBody(req),name=String(b.username||'').trim(),pw=String(b.password||'');if(!/^[A-Za-z0-9._-]{3,20}$/.test(name))return fail(res,400,'Invalid username.');if(pw.length<8||pw.length>100)return fail(res,400,'Password must be at least 8 characters.');if(await getUser(name))return fail(res,409,'That username is already taken.');const salt=crypto.randomBytes(16).toString('hex'),hash=hashPw(pw,salt),key=name.toLowerCase();try{await pool.query('INSERT INTO users(username_key,username,balance,admin,last_seen,forced,salt,hash) VALUES($1,$2,1000,false,$3,false,$4,$5)',[key,name,Date.now(),salt,hash])}catch(e){if(e.code==='23505')return fail(res,409,'That username is already taken.');throw e}const u=await getUser(name);const device=deviceOf(req)||crypto.randomBytes(32).toString('hex');await pool.query('UPDATE users SET last_ip_hash=$1,last_device_hash=$2,last_seen=$3 WHERE username_key=$4',[th(ip),th(device),Date.now(),u.username_key]);u.last_ip_hash=th(ip);u.last_device_hash=th(device);const token=await newSession(u);res.setHeader('Set-Cookie',[sessionCookie(token,req.headers['x-forwarded-proto']==='https'),`casino_device=${device}; HttpOnly; SameSite=Strict; Path=/; Max-Age=31536000${req.headers['x-forwarded-proto']==='https'?'; Secure':''}`]);return send(res,200,{user:pub(u)})}
  if(route==='POST /api/login'){const ban=await banInfo(req);if(ban)return fail(res,403,'This device/network is banned.');const ip=ipOf(req),b=await readBody(req),pw=String(b.password||'').slice(0,100),key=String(b.username||'').trim().toLowerCase().slice(0,40);if(limited('l'+ip,40,600000)||limited('la'+key,8,900000))return fail(res,429,'Too many attempts. Wait and try again.');const u=await getUser(key),ok=u?checkPw(u,pw):false;if(!ok){hit('l'+ip);hit('la'+key);return fail(res,401,'Incorrect username or password.')}const device=deviceOf(req)||crypto.randomBytes(32).toString('hex');const blocked=await pool.query('SELECT 1 FROM bans WHERE username_key=$1 LIMIT 1',[u.username_key]);if(blocked.rows[0])return fail(res,403,'This account is banned.');await pool.query('UPDATE users SET last_ip_hash=$1,last_device_hash=$2,last_seen=$3 WHERE username_key=$4',[th(ip),th(device),Date.now(),u.username_key]);u.last_ip_hash=th(ip);u.last_device_hash=th(device);const token=await newSession(u);res.setHeader('Set-Cookie',[sessionCookie(token,req.headers['x-forwarded-proto']==='https'),`casino_device=${device}; HttpOnly; SameSite=Strict; Path=/; Max-Age=31536000${req.headers['x-forwarded-proto']==='https'?'; Secure':''}`]);return send(res,200,{user:pub(u)})}
  const a=await auth(req);if(!a)return fail(res,401,'Please sign in.');const ban=await banInfo(req);if(ban)return fail(res,403,'This device/network is banned.');const u=a.u;const accountBan=await pool.query('SELECT 1 FROM bans WHERE username_key=$1 LIMIT 1',[u.username_key]);if(accountBan.rows[0]){await pool.query('DELETE FROM sessions WHERE username_key=$1',[u.username_key]);return fail(res,403,'This account is banned.');}
  if(route==='GET /api/me'){const fresh=await getUser(u.username);return send(res,200,{user:pub(fresh)})}
  if(route==='POST /api/logout'){await pool.query('DELETE FROM sessions WHERE token_hash=$1',[th(a.t)]);res.setHeader('Set-Cookie',clearSessionCookie());return send(res,200,{ok:true})}
  if(route==='POST /api/balance')return fail(res,403,'Balance is server-controlled. Use the game endpoints.');
  if(route==='POST /api/game'){if(limited('g'+u.username,30,10000))return fail(res,429,'Too many game requests. Slow down.');hit('g'+u.username);const b=await readBody(req);const out=await game(u,b);return send(res,200,out)}
  if(route==='GET /api/chat'){const after=Number(url.searchParams.get('after'))||0;const r=after===0?await pool.query('SELECT id,channel,username,message,created_at FROM chat_messages ORDER BY id DESC LIMIT 50'):await pool.query('SELECT id,channel,username,message,created_at FROM chat_messages WHERE id>$1 ORDER BY id',[after]);const out=r.rows.reverse().map(m=>({id:Number(m.id),channel:m.channel,user:m.username,text:m.message,t:Number(m.created_at)}));const on=await pool.query('SELECT username FROM users WHERE last_seen>$1 ORDER BY username',[Date.now()-45000]);return send(res,200,{messages:out,online:on.rows.map(x=>x.username)})}
  if(route==='POST /api/chat'){const b=await readBody(req),channel=String(b.channel||''),text=String(b.text||'').trim().slice(0,500);if(!CHANNELS.includes(channel))return fail(res,400,'Unknown channel.');if(!text)return fail(res,400,'Message is empty.');if(channel==='announcements'&&!u.admin)return fail(res,403,'Admins only.');if(limited('c'+u.username,3,3000))return fail(res,429,'Slow down.');hit('c'+u.username);const now=Date.now(),r=await pool.query('INSERT INTO chat_messages(channel,username,message,created_at) VALUES($1,$2,$3,$4) RETURNING id',[channel,u.username,text,now]);return send(res,200,{message:{id:Number(r.rows[0].id),channel,user:u.username,text,t:now}})}

  if(route==='GET /api/profile'){const fresh=await getUser(u.username);return send(res,200,{user:pub(fresh)})}
  if(route==='POST /api/profile'){const b=await readBody(req),p=b.profile||{};const clean={frame:String(p.frame||'neon-orbit').slice(0,40),nameStyle:String(p.nameStyle||'gradient').slice(0,40),nameColor:String(p.nameColor||'#ffd166').slice(0,20),effect:String(p.effect||'glow').slice(0,40),banner:String(p.banner||'aurora').slice(0,40),badge:String(p.badge||'✦').slice(0,8),title:String(p.title||'Rookie').slice(0,30)};await pool.query('UPDATE users SET profile=$1,title=$2 WHERE username_key=$3',[JSON.stringify(clean),clean.title,u.username_key]);return send(res,200,{user:pub({...u,profile:clean,title:clean.title})})}
  if(route==='GET /api/gartic'){let st=(await pool.query('SELECT * FROM gartic_state WHERE id=1')).rows[0];if(!st){st={id:1,prompt:'Draw a funny casino mascot',round:1,phase:'drawing',started_at:Date.now()};await pool.query('INSERT INTO gartic_state(id,prompt,round,phase,started_at) VALUES(1,$1,$2,$3,$4)',[st.prompt,st.round,st.phase,st.started_at])}const drawings=await pool.query('SELECT d.id,d.username_key,u.username,d.drawing FROM gartic_drawings d JOIN users u ON u.username_key=d.username_key WHERE d.round=$1 ORDER BY d.id',[st.round]);const votes=await pool.query('SELECT drawing_id,COUNT(*)::int count FROM gartic_votes WHERE round=$1 GROUP BY drawing_id',[st.round]);const vm={};votes.rows.forEach(v=>vm[v.drawing_id]=v.count);return send(res,200,{state:st,drawings:drawings.rows.map(d=>({id:Number(d.id),username:d.username,drawing:d.drawing,votes:vm[d.id]||0}))})}
  if(route==='POST /api/gartic/start'){if(!u.admin)return fail(res,403,'Admins only.');const prompts=['Draw a chaotic casino mascot','Draw the luckiest cat alive','Draw a ridiculous jackpot machine','Draw a space casino','Draw your dream arcade','Draw a casino boss','Draw a magical lucky coin','Draw a funny roulette table'];const prompt=prompts[rand(prompts.length)],round=Date.now();await pool.query('DELETE FROM gartic_drawings');await pool.query('DELETE FROM gartic_votes');await pool.query(`INSERT INTO gartic_state(id,prompt,round,phase,started_at) VALUES(1,$1,$2,'drawing',$3) ON CONFLICT(id) DO UPDATE SET prompt=EXCLUDED.prompt,round=EXCLUDED.round,phase='drawing',started_at=EXCLUDED.started_at`,[prompt,round,Date.now()]);return send(res,200,{ok:true})}
  if(route==='POST /api/gartic/draw'){const b=await readBody(req),drawing=String(b.drawing||'');if(drawing.length>250000)return fail(res,400,'Drawing is too large.');const st=(await pool.query('SELECT * FROM gartic_state WHERE id=1')).rows[0];if(!st)return fail(res,400,'Game is not started.');const exists=await pool.query('SELECT 1 FROM gartic_drawings WHERE round=$1 AND username_key=$2',[st.round,u.username_key]);if(exists.rows[0])return fail(res,409,'You already submitted this round.');const r=await pool.query('INSERT INTO gartic_drawings(round,username_key,drawing,created_at) VALUES($1,$2,$3,$4) RETURNING id',[st.round,u.username_key,drawing,Date.now()]);return send(res,200,{ok:true,id:Number(r.rows[0].id)})}
  if(route==='POST /api/gartic/vote'){const b=await readBody(req),id=int(b.drawingId);const st=(await pool.query('SELECT * FROM gartic_state WHERE id=1')).rows[0];if(!st)return fail(res,400,'Game is not started.');const d=await pool.query('SELECT username_key FROM gartic_drawings WHERE id=$1 AND round=$2',[id,st.round]);if(!d.rows[0])return fail(res,404,'Drawing not found.');if(d.rows[0].username_key===u.username_key)return fail(res,400,'You cannot vote for your own drawing.');await pool.query('INSERT INTO gartic_votes(round,drawing_id,username_key) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[st.round,id,u.username_key]);return send(res,200,{ok:true})}
  if(route==='POST /api/admin/logout-player'){if(!u.admin)return fail(res,403,'Admins only.');const b=await readBody(req),t=await getUser(b.username);if(!t||t.admin)return fail(res,404,'Player not found.');await pool.query('DELETE FROM sessions WHERE username_key=$1',[t.username_key]);return send(res,200,{ok:true})}
  if(route==='POST /api/admin/reset-round'){if(!u.admin)return fail(res,403,'Admins only.');const b=await readBody(req),t=await getUser(b.username);if(!t||t.admin)return fail(res,404,'Player not found.');await pool.query('DELETE FROM game_rounds WHERE username_key=$1',[t.username_key]);return send(res,200,{ok:true})}
  if(route==='POST /api/admin/announcement'){if(!u.admin)return fail(res,403,'Admins only.');const b=await readBody(req),text=String(b.text||'').trim().slice(0,500);if(!text)return fail(res,400,'Announcement required.');await pool.query(`INSERT INTO site_settings(key,value) VALUES('announcement',$1) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value`,[text]);await pool.query('INSERT INTO chat_messages(channel,username,message,created_at) VALUES($1,$2,$3,$4)',['announcements',u.username,text,Date.now()]);return send(res,200,{ok:true})}
  if(route==='GET /api/settings'){const r=await pool.query('SELECT key,value FROM site_settings');return send(res,200,{settings:Object.fromEntries(r.rows.map(x=>[x.key,x.value]))})}
  if(route==='GET /api/admin/users'){if(!u.admin)return fail(res,403,'Admins only.');const r=await pool.query('SELECT username,balance,last_ip_hash,last_device_hash FROM users WHERE admin=false ORDER BY username');return send(res,200,{users:r.rows.map(x=>({username:x.username,balance:Number(x.balance),ipHash:x.last_ip_hash||null,deviceHash:x.last_device_hash||null}))})}
  if(route==='POST /api/admin/self-balance'){if(!u.admin)return fail(res,403,'Admins only.');const b=await readBody(req),mode=String(b.mode||'');let n;if(mode==='add')n=Number(u.balance)+500;else if(mode==='reset')n=100000;else return fail(res,400,'Invalid admin action.');if(!Number.isSafeInteger(n)||n<0||n>1e12)return fail(res,400,'Invalid balance.');await pool.query('UPDATE users SET balance=$1 WHERE username_key=$2',[n,u.username_key]);return send(res,200,{balance:n})}
  if(route==='GET /api/admin/bans'){if(!u.admin)return fail(res,403,'Admins only.');const r=await pool.query('SELECT username_key,reason,created_at,ip_hash,device_hash,created_by FROM bans ORDER BY created_at DESC');return send(res,200,{bans:r.rows})}
  if(route==='POST /api/admin/ban'){if(!u.admin)return fail(res,403,'Admins only.');const b=await readBody(req),target=await getUser(b.username);if(!target||target.admin)return fail(res,404,'That player does not exist.');const reason=String(b.reason||'Admin ban').slice(0,300),ipHash=target.last_ip_hash||null,deviceHash=target.last_device_hash||null;await pool.query(`INSERT INTO bans(username_key,ip_hash,device_hash,reason,created_at,created_by) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(username_key) DO UPDATE SET ip_hash=EXCLUDED.ip_hash,device_hash=EXCLUDED.device_hash,reason=EXCLUDED.reason,created_at=EXCLUDED.created_at,created_by=EXCLUDED.created_by`,[target.username_key,ipHash,deviceHash,reason,Date.now(),u.username]);await pool.query('DELETE FROM sessions WHERE username_key=$1',[target.username_key]);await pool.query('DELETE FROM game_rounds WHERE username_key=$1',[target.username_key]);return send(res,200,{ok:true})}
  if(route==='POST /api/admin/unban'){if(!u.admin)return fail(res,403,'Admins only.');const b=await readBody(req);const key=String(b.username||'').toLowerCase();if(!key)return fail(res,400,'Username required.');await pool.query('DELETE FROM bans WHERE username_key=$1',[key]);return send(res,200,{ok:true})}
  if(route==='POST /api/admin/balance'){if(!u.admin)return fail(res,403,'Admins only.');const b=await readBody(req),t=await getUser(b.username),n=Math.floor(Number(b.balance));if(!t||t.admin)return fail(res,404,'That player does not exist.');if(!Number.isSafeInteger(n)||n<0||n>1e12)return fail(res,400,'Invalid balance.');await pool.query('UPDATE users SET balance=$1,forced=true WHERE username_key=$2',[n,t.username_key]);await pool.query('DELETE FROM game_rounds WHERE username_key=$1',[t.username_key]);return send(res,200,{ok:true})}
  return fail(res,404,'Not found');
 }catch(e){console.error(e);if(!res.headersSent)fail(res,e.status||500,e.status?e.message:'Server error')}
}
(async()=>{try{await init();const server=http.createServer((req,res)=>main(req,res));server.listen(PORT,()=>console.log('Casino running on port '+PORT));process.on('SIGTERM',async()=>{await pool.end();process.exit(0)});process.on('SIGINT',async()=>{await pool.end();process.exit(0)})}catch(e){console.error('Database startup failed:',e);process.exit(1)}})();
